#!/usr/bin/env python3
"""Parse real questions from online portals into JSON format."""
import json, os

def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# =====================================================================
# REAL IT QUESTIONS from nepallaxman.com.np (SET-1) and sumitsahani.com.np (SET-2)
# Sources:
#   https://www.nepallaxman.com.np/2023/05/computer-operator-questions-and-answers.html
#   https://www.sumitsahani.com.np/2022/01/computer-operator-question-answer-set-1.html
# =====================================================================

IT_SET1 = [
    {"id": 1, "question": "The VLSI was used in .......... generation computers.", "options": ["First", "Second", "Third", "Fourth"], "correctIndex": 3, "subject": "Computer Fundamentals", "explanation": "VLSI (Very Large Scale Integration) was used in fourth generation computers."},
    {"id": 2, "question": "Which symbol is used to represent group of any characters?", "options": ["?", "#", "*", "@"], "correctIndex": 2, "subject": "Computer Fundamentals", "explanation": "Asterisk (*) represents any group of characters."},
    {"id": 3, "question": "When was the CRAY-I super computer built?", "options": ["1960", "1976", "1980", "1985"], "correctIndex": 1, "subject": "Computer History", "explanation": "CRAY-I supercomputer was built in 1976."},
    {"id": 4, "question": "Which switch will be used in Dir to see a screenful contents of disk at a time?", "options": ["/p", " /.w", "/s", "/b"], "correctIndex": 0, "subject": "DOS Commands", "explanation": "/p switch shows one screen at a time."},
    {"id": 5, "question": "When was the P4 computer introduced?", "options": ["1980", "1990", "2000", "2004"], "correctIndex": 2, "subject": "Computer History", "explanation": "Pentium 4 was introduced in 2000."},
    {"id": 6, "question": "Which is not invalid user file name?", "options": ["Raj.exe", "Ram.txt", "Kumar.sys", "Rajan.com"], "correctIndex": 1, "subject": "Operating System", "explanation": "Ram.txt is a valid filename."},
    {"id": 7, "question": "The memory serves as a buffer between processor and memory is..........", "options": ["Virtual memory", "Flash memory", "Cache memory", "RAM"], "correctIndex": 2, "subject": "Computer Memory", "explanation": "Cache memory acts as a buffer between CPU and main memory."},
    {"id": 8, "question": "Which is not valid alphabet for attribute setting?", "options": ["R", "S", "H", "C"], "correctIndex": 3, "subject": "DOS Commands", "explanation": "C is not a valid attribute letter (R=Read-only, S=System, H=Hidden)."},
    {"id": 9, "question": "The memory which allocate space for DOS and application is called..........", "options": ["Expanded memory", "Cache memory", "Virtual memory", "Conventional memory"], "correctIndex": 3, "subject": "Computer Memory", "explanation": "Conventional memory is used by DOS and applications."},
    {"id": 10, "question": "Which will not create a sub directory on disk?", "options": ["Mkdir", "Md", "Chdir", "All of the above"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Chdir (cd) only changes directory, does not create one."},
    {"id": 11, "question": "The data density of tape is measured in..........", "options": ["Bits per inch", "Bytes per inch", "Record per inch", "None"], "correctIndex": 0, "subject": "Storage Devices", "explanation": "Tape density is measured in bits per inch (BPI)."},
    {"id": 12, "question": "The command sorts the fragments of file and enhanced the performance of disk is..........", "options": ["Scandisk", "Chkdsk", "Defrag", "Sys"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Defrag defragments files to improve disk performance."},
    {"id": 13, "question": "Which directory can not be created by MD command?", "options": ["Sub directory", "Root Directory", "Child Directory", "None"], "correctIndex": 1, "subject": "DOS Commands", "explanation": "Root directory already exists and cannot be created by MD."},
    {"id": 14, "question": "Which is the system software?", "options": ["Operating system", "Compiler", "Utilities", "All of the above"], "correctIndex": 3, "subject": "System Software", "explanation": "Operating system, compiler and utilities are all system software."},
    {"id": 15, "question": "The command allows you to show the status of disk.", "options": ["Vol", "Diskcomp", "Chkdsk", "Defrag"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Chkdsk checks disk status and file system integrity."},
    {"id": 16, "question": "The most of the input devices consist .......... for signal conversion.", "options": ["Encoder", "Decoder", "Modem", "None"], "correctIndex": 0, "subject": "Input Devices", "explanation": "Input devices use encoders to convert signals."},
    {"id": 17, "question": "What will be the command if you want to copy ra.doc file that resides in the floppy disk into work sub-directory of hard-disk while you are in c-prompt.", "options": ["Copy c:/ra.doc a:/work", "Copy a:/ra.doc c:/work", "Copy ra.doc c:/work", "Copy c:/work a:/ra.doc"], "correctIndex": 1, "subject": "DOS Commands", "explanation": "Copy from source a:/ra.doc to destination c:/work."},
    {"id": 18, "question": "The latest 16-bit Unicode can represent the .......... symbols.", "options": ["256", "32567", "40000", "65536"], "correctIndex": 3, "subject": "Computer Fundamentals", "explanation": "16-bit Unicode can represent 2^16 = 65536 symbols."},
    {"id": 19, "question": "The system files are resides in the .......... after booting process.", "options": ["ROM", "Processor", "RAM", "Hard disk"], "correctIndex": 2, "subject": "Computer Memory", "explanation": "System files are loaded into RAM after booting."},
    {"id": 20, "question": "The input device is used for examination paper.", "options": ["OMR", "Light pen", "OCR", "MICR"], "correctIndex": 0, "subject": "Input Devices", "explanation": "OMR (Optical Mark Recognition) is used for reading examination papers."},
    {"id": 21, "question": "The break checking command is..........", "options": ["Ctrl+C", "Ctrl+B", "Ctrl+Z", "All of the above"], "correctIndex": 0, "subject": "DOS Commands", "explanation": "Ctrl+C is used to break/terminate a running command."},
    {"id": 22, "question": "The full form of MICR is..........", "options": ["Magnetic Ink Character Reader", "Magnetic Ink Character Recognition", "Magnetic Ink Coding Reader", "Magnet Ink Character Recognition"], "correctIndex": 1, "subject": "Input Devices", "explanation": "MICR = Magnetic Ink Character Recognition."},
    {"id": 23, "question": "The .......... enables the user to load device drivers and programs into upper memory area while running DOS in 386 or higher microprocessor.", "options": ["Himem.sys", "Emm386.exe", "Config.sys", "All of the above"], "correctIndex": 1, "subject": "DOS Configuration", "explanation": "Emm386.exe manages extended memory and upper memory blocks."},
    {"id": 24, "question": "Which one is fast accessible?", "options": ["RAM", "Register", "Hard disk", "Tape"], "correctIndex": 1, "subject": "Computer Memory", "explanation": "CPU registers are the fastest accessible memory."},
    {"id": 25, "question": "The command will display the history of operating system.", "options": ["Chkdsk", "Mem", "Vol", "Ver"], "correctIndex": 3, "subject": "DOS Commands", "explanation": "Ver command displays the DOS version information."},
    {"id": 26, "question": "The branch of science that deals with helping machine to solve complex problems like human fashion.", "options": ["Genetic Science", "Artificial Intelligence", "Computer Science", "All of the above"], "correctIndex": 1, "subject": "Computer Science", "explanation": "Artificial Intelligence deals with machine problem-solving like humans."},
    {"id": 27, "question": "The Highest digit symbol of hexadecimal is..........", "options": ["9", "16", "F", "E"], "correctIndex": 2, "subject": "Number Systems", "explanation": "Hexadecimal digits go from 0-9 and A-F; F is the highest (15)."},
    {"id": 28, "question": "The data transfer rate of USB cable is measured in terms of .......... bit per second.", "options": ["Mega", "Kilo", "Giga", "Milli"], "correctIndex": 0, "subject": "Computer Hardware", "explanation": "USB data transfer rate is measured in Megabits per second (Mbps)."},
    {"id": 29, "question": "Which is an internal command?", "options": ["Label", "Mem", "Path", "Sys"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Path is an internal DOS command."},
    {"id": 30, "question": "The output device is used for meeting and conference.", "options": ["Monitor", "Printer", "Plotter", "LCD projector"], "correctIndex": 3, "subject": "Output Devices", "explanation": "LCD projector is used for presentations in meetings and conferences."},
    {"id": 31, "question": "The system software which translates an instruction at a time from source program and execute it.", "options": ["Translator", "Compiler", "Interpreter", "Assembler"], "correctIndex": 2, "subject": "System Software", "explanation": "Interpreter translates and executes one instruction at a time."},
    {"id": 32, "question": "The multi-user operating system is..........", "options": ["Linux", "Unix", "Windows 2000", "All of the above"], "correctIndex": 3, "subject": "Operating System", "explanation": "Linux, Unix and Windows 2000 all support multiple users."},
    {"id": 33, "question": "Which is not function of operating system?", "options": ["Managing application", "Detecting errors", "Managing memory and files", "Detecting virus"], "correctIndex": 3, "subject": "Operating System", "explanation": "Detecting virus is the function of antivirus software, not the OS."},
    {"id": 34, "question": "The software are made available free of charge on trial based software are called..........", "options": ["Firmware", "Shareware", "Application software", "System Software"], "correctIndex": 1, "subject": "Software Types", "explanation": "Shareware is trial-based software available for free initially."},
    {"id": 35, "question": "When was MS-Windows introduced?", "options": ["1975", "1980", "1985", "1995"], "correctIndex": 2, "subject": "Computer History", "explanation": "Microsoft Windows was introduced in 1985 (Windows 1.0)."},
    {"id": 36, "question": "The second generation computer is..........", "options": ["IBM-702", "IBM-1400", "IBM system/360", "IBM system/370"], "correctIndex": 1, "subject": "Computer History", "explanation": "IBM-1400 series belongs to second generation computers."},
    {"id": 37, "question": "Which is the backup storage device?", "options": ["ROM", "RAM", "Floppy", "Register"], "correctIndex": 2, "subject": "Storage Devices", "explanation": "Floppy disk is a backup/storage device."},
    {"id": 38, "question": "The command fixes the errors of disk.", "options": ["ErrorFix", "Scandisk", "Chkdsk", "Defrag"], "correctIndex": 1, "subject": "DOS Commands", "explanation": "Scandisk checks and fixes disk errors."},
    {"id": 39, "question": "The command is used to remove sub-directory which contains some files.", "options": ["RD", "RMDir", "Deltree", "Erase"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Deltree removes directories including their contents."},
    {"id": 40, "question": "The high speed and capable to support large number of devices is..........", "options": ["USB", "Parallel", "Serial", "SCSI"], "correctIndex": 0, "subject": "Computer Hardware", "explanation": "USB supports high speed and multiple devices."},
    {"id": 41, "question": "Which command is used to go to parent directory from its sub-directory?", "options": ["Cd", "CD/", "Cd..", "None"], "correctIndex": 2, "subject": "DOS Commands", "explanation": "Cd.. moves to the parent directory."},
    {"id": 42, "question": "The microprocessor contains the millions of..........", "options": ["Registers", "Transistors", "Capacitors", "All of the above"], "correctIndex": 1, "subject": "Computer Hardware", "explanation": "Modern microprocessors contain millions of transistors."},
    {"id": 43, "question": "Which is the characteristic of computer?", "options": ["Accuracy", "Reliability", "Speed", "All of the above"], "correctIndex": 3, "subject": "Computer Fundamentals", "explanation": "Accuracy, reliability and speed are all characteristics of computers."},
    {"id": 44, "question": "The term Gigabytes refers to..........", "options": ["1024 bytes", "1024 kilobytes", "1024 megabytes", "1024 megabits"], "correctIndex": 2, "subject": "Computer Memory", "explanation": "1 GB = 1024 MB (megabytes)."},
    {"id": 45, "question": "The assembly language uses the..........", "options": ["Machine code", "Rough code", "Human code", "Mnemonic code"], "correctIndex": 3, "subject": "Programming", "explanation": "Assembly language uses mnemonic codes."},
    {"id": 46, "question": "The video display adapter does not support..........", "options": ["4-bit", "8-bit", "12-bit", "16-bit"], "correctIndex": 2, "subject": "Computer Hardware", "explanation": "12-bit is not a standard video display adapter mode."},
    {"id": 47, "question": "Which is not input device?", "options": ["Digitizer", "Data glove", "Sensors", "Voice synthesis"], "correctIndex": 3, "subject": "Input/Output Devices", "explanation": "Voice synthesis is an output device, not input."},
    {"id": 48, "question": "The most popular keyboard type is..........", "options": ["QWERTY", "PQRSTY", "Ergonomic", "IBM"], "correctIndex": 0, "subject": "Input Devices", "explanation": "QWERTY is the most popular keyboard layout."},
    {"id": 49, "question": "The permanent memory which exhibits characteristics of RAM is..........", "options": ["Cache memory", "Virtual memory", "Base memory", "Internal memory"], "correctIndex": 1, "subject": "Computer Memory", "explanation": "Virtual memory uses disk space like RAM."},
    {"id": 50, "question": "Which is not true for speed of CPU?", "options": ["System Clock rate", "Bus width", "Word length", "Price of CPU"], "correctIndex": 3, "subject": "Computer Hardware", "explanation": "Price of CPU does not determine its speed."},
]

IT_SET2 = [
    {"id": 1, "question": "Which one is true for password?", "options": ["Passwords are case sensitive", "Has fixed length", "Can contain letters, numbers and symbols", "All of the above"], "correctIndex": 3, "subject": "Computer Security", "explanation": "Passwords are case sensitive, can have variable length, and contain letters, numbers and symbols."},
    {"id": 2, "question": "Which is not an operator?", "options": [";", "%", "/", ","], "correctIndex": 0, "subject": "Programming", "explanation": "Semicolon is a statement terminator, not an operator."},
    {"id": 3, "question": "The orientation of the page in which the printed lines run the width of the page is called..........", "options": ["Landscape", "Inverted", "Normal", "Portrait"], "correctIndex": 0, "subject": "Word Processing", "explanation": "Landscape orientation has lines running across the width."},
    {"id": 4, "question": "The labels defining in a worksheet structure", "options": ["Contain letters, numbers and symbols", "Are comprised of numbers and the equals sign", "Include function", "Begin with and equals sign"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Labels in worksheet begin with an equals sign (=)."},
    {"id": 5, "question": "To move to the last column in a worksheet, press..........", "options": ["Ctrl+Home", "Ctrl+End", "Alt+Right Arrow", "Alt+Down Arrow"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Ctrl+End moves to the last used cell."},
    {"id": 6, "question": "What will be happen when you click the border between two columns?", "options": ["Widen the column width as contents", "Widen the row height as contents", "Hide the row", "Both (A) and (C)"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Double-clicking column border auto-fits column width."},
    {"id": 7, "question": "A worksheet contains approximately how many rows?", "options": ["256", "65535", "65635", "65536"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Excel worksheet contains 65536 rows."},
    {"id": 8, "question": "To select multiple, non-adjacent worksheets in a workbook.", "options": ["Press Ctrl and click another tab", "Press Alt and click another tab", "Press Shift and click another tab", "Drag the mouse pointer through the tabs"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Ctrl+Click selects non-adjacent worksheet tabs."},
    {"id": 9, "question": "By default, how is text horizontal aligned inside a cell in Excel?", "options": ["Left aligned", "Center", "Right aligned", "Justified"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Text is left-aligned by default in Excel."},
    {"id": 10, "question": "Which option restrict the values that can be entered into a cell?", "options": ["Data > Validation", "Data > Filter > Advanced Filter", "Format > Cells", "Format > Conditional Formatting"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Data Validation restricts cell input values."},
    {"id": 11, "question": "To display the heading as slanted text to save space..........", "options": ["Select slanted Text on the font tab", "Select Text Orientation on the Alignment tab", "Superscript on the font tab", "Center Across selection on the Alignment tab"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Text Orientation on Alignment tab allows slanted headings."},
    {"id": 12, "question": "What will be the correct answer, if user enters the 3 P into a cell?", "options": ["3.00", "3:00 PM", "3 P", "None of above"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Excel interprets '3 P' as 3:00 PM time format."},
    {"id": 13, "question": "The formula uses its own reference is called..........", "options": ["Absolute reference", "Mixed reference", "External reference", "Circular reference"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "A formula referring to its own cell creates a circular reference."},
    {"id": 14, "question": "What is the function of text to column?", "options": ["Allows you to separate delimited text across the columns automatically", "Converts the selected text to table", "It automatically resizes the cell size whenever a large text is added in the cell", "None of the above"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Text to Columns splits delimited text into separate columns."},
    {"id": 15, "question": "The maximum number of characters can be stored in a cell is..........", "options": ["256", "32000", "65000", "None of the above"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Excel cell can store up to 32000 characters."},
    {"id": 16, "question": "Goal Seek appears at the.......... Menu", "options": ["File", "Data", "Tools", "Format"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "Goal Seek is found in the Tools menu."},
    {"id": 17, "question": "Which shortcut key is used to hide column?", "options": ["Alt+9", "Ctrl+9", "Alt+0", "Ctrl+0"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Ctrl+9 hides the selected column in Excel."},
    {"id": 18, "question": "The maximum length of formula is..........", "options": ["1024 characters", "255 characters", "2000 characters", "Depends upon internal memory"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Maximum formula length in Excel is 1024 characters."},
    {"id": 19, "question": "The shortcut key define name is..........", "options": ["Ctrl+F2", "Ctrl+F3", "Ctrl+F4", "Ctrl+F9"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Ctrl+F3 opens the Define Name dialog."},
    {"id": 20, "question": "The maximum number of sheet within any workbook is..........", "options": ["100", "200", "255", "Unlimited"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Modern Excel allows unlimited sheets (previously 255)."},
    {"id": 21, "question": "The format dddd in date will display..........", "options": ["Sund", "Sun", "Sunday", "None of the above"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "dddd format displays full day name like Sunday."},
    {"id": 22, "question": "The key press moves the cell pointer on pane of another pane in split window.", "options": ["F5", "F6", "F9", "F11"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "F6 moves between panes in a split window."},
    {"id": 23, "question": "The referencing styles used in Excel..........", "options": ["1", "2", "3", "4"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Excel uses A1 and R1C1 referencing styles (2 styles)."},
    {"id": 24, "question": "To insert Auto sum function, one can press..........", "options": ["Alt++", "Alt+=", "Alt+Enter", "Alt+;"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Alt+= inserts the AutoSum function."},
    {"id": 25, "question": "The category axis is also called a..........", "options": ["X-Axis", "Y-Axis", "Secondary Axis", "Value Axis"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Category axis is also known as X-Axis."},
    {"id": 26, "question": "The shortcut key is used to create default chart is..........", "options": ["F11", "Alt+F1", "F10", "A & B"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Both F11 and Alt+F1 create default charts in Excel."},
    {"id": 27, "question": "The file extension of workspace file is..........", "options": [".xls", ".xlt", ".xlw", ".xls"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "Excel workspace file extension is .xlw."},
    {"id": 28, "question": "The shortcut key is used to switch contents in to the edit mode..........", "options": ["F2", "F3", "F4", "F6"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "F2 switches cell to edit mode."},
    {"id": 29, "question": "Which one of Excel window allows you to enter values in worksheet?", "options": ["Title Bar", "Menu Bar", "Formula Bar", "Standard Tool Bar"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "Formula Bar allows entering values directly."},
    {"id": 30, "question": "A typical worksheet has number of columns.", "options": ["23", "256", "255", "1024"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Excel worksheet has 256 columns."},
    {"id": 31, "question": "Comments put in cells are called..........", "options": ["Smart Tip", "Cell Tip", "Web Tip", "Soft Tip"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Cell comments appear as Cell Tips on hover."},
    {"id": 32, "question": "Getting data from a cell located in a different sheet is called..........", "options": ["Accessing", "Referencing", "Updating", "Functioning"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Getting data from another sheet is called referencing."},
    {"id": 33, "question": "Which of the following is not a valid data type in Excel?", "options": ["Number", "Hyperlink", "Label", "Date/Time"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Hyperlink is not a data type; it is an object/feature."},
    {"id": 34, "question": "Which elements of a worksheet can be protected from accidental modification?", "options": ["Contents", "Object", "Scenarios", "All of the above"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Contents, objects, and scenarios can all be protected."},
    {"id": 35, "question": "A numeric value can be treated as a label value if it is preceded with..........", "options": ["'", "!", "\"", "~"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Preceding a number with apostrophe treats it as text/label."},
    {"id": 36, "question": "Which is text operator?", "options": ["Apostrophe", "Exclamation", "Hash", "Ampersand"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Ampersand (&) is the text concatenation operator in Excel."},
    {"id": 37, "question": "Which formula returns multiple results from single formula?", "options": ["Standard Formula", "Array Formula", "Mixed Formula", "Smart Formula"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Array formulas can return multiple results from a single formula."},
    {"id": 38, "question": "Which is not tool for what-if analysis?", "options": ["Table", "Goal Seek", "Pivot table", "Scenario"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "Pivot table is for data summarization, not what-if analysis."},
    {"id": 39, "question": "Data can be added from different sheet within a workbook using..........", "options": ["Data outline", "Data consolidate", "Data Subtotal", "Scenario"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Data Consolidate combines data from multiple sheets."},
    {"id": 40, "question": "The Edit > Delete command will delete..........", "options": ["Delete sheet", "Clear contents", "Delete cell", "All of the above"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Edit > Delete can delete sheet, contents, or cells."},
    {"id": 41, "question": "Data of sheet can be printed on center of page using..........", "options": ["Page setup / Margin", "Print / Center", "Page setup / Layout", "Page setup / Sheet"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Page Setup > Margin settings center content on page."},
    {"id": 42, "question": "To import data for database in excel using..........", "options": ["Data / Import external data", "Tools / Get external data", "Tools / Import external data", "None of the above"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "Data > Import External Data is used to import database data."},
    {"id": 43, "question": "The mode of operations can be display at..........", "options": ["Formula bar", "Status bar", "Display bar", "Scroll bar"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Status bar displays the current mode of operation."},
    {"id": 44, "question": "AutoSum button appears at the toolbar.", "options": ["Standard", "Formula", "Formatting", "Border"], "correctIndex": 0, "subject": "Spreadsheet", "explanation": "AutoSum button appears on the Standard toolbar."},
    {"id": 45, "question": "You can enable auto save feature using..........", "options": ["Add-ins", "Attachment", "Option", "None of the above"], "correctIndex": 2, "subject": "Spreadsheet", "explanation": "AutoSave settings are found in Options."},
    {"id": 46, "question": "The insert function appears at the..........", "options": ["Standard toolbar", "Formula palette", "Formatting toolbar", "None of the above"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Insert Function appears in the Formula palette."},
    {"id": 47, "question": "Which command will display the subset of data from list?", "options": ["Pivot Table", "Filter", "Goal Seek", "Scenario"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Filter command displays a subset of data from a list."},
    {"id": 48, "question": "Which one you can search by find command?", "options": ["Formula", "Value", "Comment", "All of the above"], "correctIndex": 3, "subject": "Spreadsheet", "explanation": "Find command can search formulas, values, and comments."},
    {"id": 49, "question": "Which will affects the column width of entire worksheet?", "options": ["Column width", "Standard width", "Global width", "All of the above"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "Standard width affects the default column width of entire worksheet."},
    {"id": 50, "question": "Which symbol will display when your number is too larger than column width?", "options": ["$", "#", "@", "*"], "correctIndex": 1, "subject": "Spreadsheet", "explanation": "# symbols appear when a number is too wide for the column."},
]

# Write IT sets
write_json("data/en/it/set4.json", IT_SET1)
write_json("data/ne/it/set4.json", IT_SET1)
write_json("data/en/it/set5.json", IT_SET2)
write_json("data/ne/it/set5.json", IT_SET2)
print("Wrote IT set4 and set5 (100 real questions from nepallaxman.com.np + sumitsahani.com.np)")

# =====================================================================
# REAL NURSING QUESTIONS from gyanmark.com
# Sources:
#   https://gyanmark.com/blogs/staff-nurse-loksewa-exam-questions-nursing-loksewa-preparation
#   https://gyanmark.com/blogs/staff-nurse-psc-exam-model-questions-staff-nurse-psc-exam-preparation
# =====================================================================

NURSING_SET1 = [
    {"id": 1, "question": "Which is the largest muscle?", "options": ["Gluteus maximus", "Sartorius", "Masseter", "Stapedius"], "correctIndex": 0, "subject": "Anatomy", "explanation": "Gluteus maximus is the largest muscle in the human body."},
    {"id": 2, "question": "Which is not a special sense organ in the sensory system?", "options": ["Teeth", "Skin", "Tongue", "Eye"], "correctIndex": 0, "subject": "Anatomy", "explanation": "Teeth are not classified as special sense organs."},
    {"id": 3, "question": "Which is the longest organ of the digestive system in the human body?", "options": ["Oesophagus", "Stomach", "Small intestine", "Large intestine"], "correctIndex": 2, "subject": "Anatomy", "explanation": "Small intestine is the longest organ of the digestive system."},
    {"id": 4, "question": "What are the main activities of digestive system?", "options": ["Ingestion", "Digestion", "Both (A) and (B)", "Expression"], "correctIndex": 2, "subject": "Physiology", "explanation": "Digestive system performs ingestion and digestion."},
    {"id": 5, "question": "Length of female urethra is", "options": ["18 cm", "12 cm", "8 cm", "4 cm"], "correctIndex": 3, "subject": "Anatomy", "explanation": "Female urethra is approximately 4 cm long."},
    {"id": 6, "question": "The life span of erythrocytes is", "options": ["60 Days", "90 Days", "120 Days", "125 Days"], "correctIndex": 2, "subject": "Physiology", "explanation": "Red blood cells (erythrocytes) live about 120 days."},
    {"id": 7, "question": "The process of Bone formation is called", "options": ["Ossification", "Calcification", "Osteoid formation", "Epiphyseal plate"], "correctIndex": 0, "subject": "Anatomy", "explanation": "Ossification is the process of bone formation."},
    {"id": 8, "question": "What are the sign of Cushing Syndrome?", "options": ["Large thighs", "Pendulous abdomen", "Large upper arms", "Posterior neck fat pad and thin extremities"], "correctIndex": 3, "subject": "Pathology", "explanation": "Cushing syndrome features buffalo hump and thin extremities."},
    {"id": 9, "question": "Which of the following disease is not included in the respiratory system?", "options": ["Epilepsy", "Bronchitis", "Pulmonary TB", "Pleurisy"], "correctIndex": 0, "subject": "Disease Classification", "explanation": "Epilepsy is a neurological disorder, not respiratory."},
    {"id": 10, "question": "How many steps should be followed for home delivery services?", "options": ["3", "5", "7", "10"], "correctIndex": 0, "subject": "Midwifery", "explanation": "Home delivery service follows 3 main steps."},
    {"id": 11, "question": "Which is not the major killer disease?", "options": ["Diarrhoea", "Measles", "Tuberculosis", "Scabies"], "correctIndex": 3, "subject": "Community Health", "explanation": "Scabies is not a major killer disease."},
    {"id": 12, "question": "When was the national health policy adopted in BS?", "options": ["2046", "2048", "2050", "2063"], "correctIndex": 1, "subject": "Health Policy", "explanation": "National health policy was adopted in 2048 BS."},
    {"id": 13, "question": "What are the Sources of the data collection?", "options": ["Patient", "Patient's family", "Patient's charts and Records", "All of the above"], "correctIndex": 3, "subject": "Nursing Research", "explanation": "Data can be collected from patient, family, and records."},
    {"id": 14, "question": "Where is the remittent fever seen?", "options": ["Typhoid fever", "Rheumatic fever", "TB", "Malaria"], "correctIndex": 0, "subject": "Pathology", "explanation": "Remittent fever is characteristic of typhoid."},
    {"id": 15, "question": "When is world health day celebrated?", "options": ["7th April Each Year", "10th April Each Year", "15th April Each Year", "20th April Each year"], "correctIndex": 0, "subject": "Health Awareness", "explanation": "World Health Day is celebrated on 7th April."},
    {"id": 16, "question": "Full liquid diet contains", "options": ["Carbohydrate", "Fat", "Protein", "All of the above"], "correctIndex": 3, "subject": "Nutrition", "explanation": "Full liquid diet contains carbohydrates, fats, and proteins."},
    {"id": 17, "question": "The Yellow fever is transmitted by the bite of", "options": ["Mites", "Rat", "Aedes Mosquito", "Lice"], "correctIndex": 2, "subject": "Communicable Diseases", "explanation": "Yellow fever is transmitted by Aedes mosquito."},
    {"id": 18, "question": "What is the study of fungus called?", "options": ["Fungology", "Mycology", "Mythology", "Algology"], "correctIndex": 1, "subject": "Microbiology", "explanation": "Mycology is the study of fungi."},
    {"id": 19, "question": "What are the signs of severe dehydration?", "options": ["Skin pinch goes back slowly", "Lethargic or unconscious baby", "Thirsty", "All of the above"], "correctIndex": 1, "subject": "Pediatrics", "explanation": "Lethargy or unconsciousness indicates severe dehydration."},
    {"id": 20, "question": "Inflammation of the brain tissue is called", "options": ["Meningitis", "Encephalitis", "Encephalosis", "Epilepsy"], "correctIndex": 1, "subject": "Neurology", "explanation": "Encephalitis is inflammation of brain tissue."},
    {"id": 21, "question": "In Nepal, DOTS programme was successfully implemented throughout the country in", "options": ["2000", "2001", "2002", "2003"], "correctIndex": 1, "subject": "Health Program", "explanation": "DOTS programme was implemented throughout Nepal in 2001."},
    {"id": 22, "question": "The influenza is caused by", "options": ["Virus", "Bacteria", "Protozoa", "Fungi"], "correctIndex": 0, "subject": "Microbiology", "explanation": "Influenza is caused by influenza virus."},
    {"id": 23, "question": "All organs are affected in hypertension except?", "options": ["Eye", "Brain", "Liver", "Heart"], "correctIndex": 2, "subject": "Cardiology", "explanation": "Liver is not primarily affected by hypertension."},
    {"id": 24, "question": "Rainbow like vision is seen in", "options": ["Trachoma", "Glaucoma", "Cataract", "Corneal ulcer"], "correctIndex": 1, "subject": "Ophthalmology", "explanation": "Rainbow halos around lights are a sign of glaucoma."},
    {"id": 25, "question": "The Study of epidemiology is called", "options": ["Disease Frequency", "Disease study", "Disease control only", "Data analysis"], "correctIndex": 0, "subject": "Epidemiology", "explanation": "Epidemiology studies disease frequency in populations."},
    {"id": 26, "question": "IUCD works for family planning for", "options": ["5 Years", "8 Years", "10 Years", "12 Years"], "correctIndex": 2, "subject": "Family Planning", "explanation": "Intrauterine Contraceptive Device (IUCD) typically works for 10 years."},
    {"id": 27, "question": "How many tools are included in the supervision activities in Nursing programme?", "options": ["9", "10", "11", "12"], "correctIndex": 1, "subject": "Nursing Management", "explanation": "Nursing supervision activities include 10 tools."},
    {"id": 28, "question": "How many Steps should be followed for community diagnosis?", "options": ["8", "10", "15", "7"], "correctIndex": 1, "subject": "Community Health", "explanation": "Community diagnosis follows 10 steps."},
    {"id": 29, "question": "How many sources are used in health information system in health sector?", "options": ["9", "10", "15", "20"], "correctIndex": 0, "subject": "Health Information", "explanation": "Health information system uses 9 sources."},
    {"id": 30, "question": "All are killed vaccine except", "options": ["BCG", "IPV", "Meningitis", "Rabies vaccine"], "correctIndex": 0, "subject": "Immunization", "explanation": "BCG is a live attenuated vaccine; others listed are killed vaccines."},
    {"id": 31, "question": "When was the first case of AIDS detected in Nepal?", "options": ["1978", "1988", "1998", "1968"], "correctIndex": 1, "subject": "Epidemiology", "explanation": "First AIDS case in Nepal was detected in 1988."},
    {"id": 32, "question": "It is formed by the two innominate bones which articulate anteriorly at the symphasis pubis and posteriorly with the sacrum.", "options": ["Humerus", "Femur", "The pelvis", "Thoracic cage"], "correctIndex": 2, "subject": "Anatomy", "explanation": "The pelvis is formed by innominate bones and sacrum."},
    {"id": 33, "question": "Caput succedaneum of a neonate disappears after how many hours after birth?", "options": ["40 hrs", "24 Hrs", "80 hrs", "90 hrs"], "correctIndex": 2, "subject": "Neonatology", "explanation": "Caput succedaneum typically resolves within 80 hours."},
    {"id": 34, "question": "When was the national safe motherhood programme initiated?", "options": ["1996", "1997", "1990", "2000"], "correctIndex": 1, "subject": "Health Program", "explanation": "National Safe Motherhood Programme was initiated in 1997."},
    {"id": 35, "question": "For non-immunized pregnant woman 2 doses of 0.5ml of TT is given at", "options": ["20-24 Weeks", "30-36 Weeks", "12-16 Weeks", "8-12 Weeks"], "correctIndex": 0, "subject": "Immunization", "explanation": "TT vaccine for non-immunized pregnant women is given at 20-24 weeks."},
    {"id": 36, "question": "At birth, the length of the baby measures about", "options": ["25 cm", "50 cm", "75 cm", "100 cm"], "correctIndex": 1, "subject": "Neonatology", "explanation": "Average birth length of a baby is about 50 cm."},
    {"id": 37, "question": "In teaching deep breathing and coughing exercise to a client which teaching method can be best used?", "options": ["Role play", "Discussion", "Exhibition", "Demonstration"], "correctIndex": 3, "subject": "Nursing Education", "explanation": "Demonstration is the best method for teaching breathing exercises."},
    {"id": 38, "question": "Abortion is defined as the loss of pregnancy before the fetal is weeks of gestation", "options": ["20 weeks", "22 Weeks", "28 Weeks", "36 Weeks"], "correctIndex": 1, "subject": "Obstetrics", "explanation": "Abortion is defined as pregnancy loss before 22 weeks."},
    {"id": 39, "question": "Which of the following selects the female community health volunteer?", "options": ["VDC Chairman", "Member of mother group", "MCHW", "VHW"], "correctIndex": 1, "subject": "Community Health", "explanation": "Female Community Health Volunteers are selected by mother groups."},
    {"id": 40, "question": "What incentive to the mother is given after delivery at health facilities?", "options": ["Rs.1500 in mountains, Rs.1000 in hill, Rs 500 in tarai", "Rs.500 in mountain, Rs 1000 in hills, Rs 1500 in tarai", "Rs.1000 in Mountain, Rs 500 in hill, Rs.1500 in tarai", "Rs.800 in Mountain, Rs.1000 in hill, Rs.500 in tarai"], "correctIndex": 0, "subject": "Health Policy", "explanation": "Delivery incentives vary by region: Rs.1500 (mountain), Rs.1000 (hill), Rs.500 (tarai)."},
    {"id": 41, "question": "Within 3 minutes after birth, the normal heart rate of the infant may range between", "options": ["100-130 Beats per minute", "100-180 beats per minute", "120-160 Beats per minute", "130-170 Beats per minute"], "correctIndex": 2, "subject": "Neonatology", "explanation": "Normal newborn heart rate is 120-160 bpm."},
    {"id": 42, "question": "One of the most common cause of hypotonic uterine dystocia is?", "options": ["Twin gestation", "Maternal anemia", "Pelvic contracture", "Pregnancy induced hypertension"], "correctIndex": 0, "subject": "Obstetrics", "explanation": "Twin gestation is a common cause of hypotonic uterine dystocia."},
    {"id": 43, "question": "Which of the following is antipsychiatric drug?", "options": ["Diazepam", "Chlorpromazine", "Librium", "Lithium bicarbonate"], "correctIndex": 1, "subject": "Pharmacology", "explanation": "Chlorpromazine is an antipsychotic drug."},
    {"id": 44, "question": "A positive nursing action when caring for a middle aged depressed client is to?", "options": ["Play chess with the client", "Allow the client to make personal decision", "Give company to client as often as possible", "Provide the client with frequent period of thinking time"], "correctIndex": 2, "subject": "Psychiatric Nursing", "explanation": "Providing company is a positive nursing action for depressed clients."},
    {"id": 45, "question": "The process of influencing group activities towards accomplishment of goals in a given situation is:", "options": ["Leader", "Leadership", "Management", "Manager"], "correctIndex": 1, "subject": "Nursing Management", "explanation": "Leadership is influencing group activities toward goal accomplishment."},
    {"id": 46, "question": "Muscle tone is recorded by the", "options": ["Electro Encephalo Graphy (EEG)", "Electro Cardio Graphy (ECG)", "Electro Oculo Graphy (EoG)", "Electro Myo Graphy (EMG)"], "correctIndex": 3, "subject": "Diagnostic Tests", "explanation": "EMG records muscle tone and electrical activity."},
    {"id": 47, "question": "Following vaccines are live attenuated vaccines except", "options": ["BCG", "Oral polio", "Japanese encephalitis", "Tetanus"], "correctIndex": 3, "subject": "Immunization", "explanation": "Tetanus toxoid is not a live attenuated vaccine."},
    {"id": 48, "question": "Trachoma is a chronic infectious disease caused by chlamydia trachomatis, it is a disease of", "options": ["Eye", "Lungs", "Nose", "Ear"], "correctIndex": 0, "subject": "Ophthalmology", "explanation": "Trachoma is an eye disease caused by Chlamydia trachomatis."},
    {"id": 49, "question": "The study of osteology is called", "options": ["Bone", "Joint", "Muscle", "Nerve"], "correctIndex": 0, "subject": "Anatomy", "explanation": "Osteology is the study of bones."},
    {"id": 50, "question": "Endometriosis is characterized by", "options": ["Amenorrhoea and insomnia", "Ecchymosis and petechiae", "Painful menstruation and backache", "Early osteoporosis and pelvic inflammations"], "correctIndex": 2, "subject": "Gynecology", "explanation": "Endometriosis is characterized by painful menstruation and backache."},
]

NURSING_SET2 = [
    {"id": 1, "question": "Most common cause of Diabetic ketoacidosis is due to", "options": ["Emotional stress", "Presence of infection", "Increased insulin dose", "Inadequate food intake"], "correctIndex": 1, "subject": "Pathology", "explanation": "Infection is the most common cause of diabetic ketoacidosis."},
    {"id": 2, "question": "Breast milk is rich in all except", "options": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "correctIndex": 3, "subject": "Nutrition", "explanation": "Breast milk is low in Vitamin D."},
    {"id": 3, "question": "Breast Cancer is epidemiologically common with", "options": ["Multiparity", "Nulliparity", "Alcoholic", "Married woman"], "correctIndex": 1, "subject": "Oncology", "explanation": "Nulliparity (never having given birth) is a risk factor for breast cancer."},
    {"id": 4, "question": "Pediatric AIDS is mainly due to", "options": ["Blood transfusion", "Transplacental", "Sexual intercourse", "Organ transplantation"], "correctIndex": 1, "subject": "Pediatrics", "explanation": "Pediatric AIDS is mainly transmitted from mother to child (transplacental)."},
    {"id": 5, "question": "Another name of hook worm infestation is", "options": ["Ascariasis", "Ancylostomiasis", "Salinatolysis", "Leishmaniasis"], "correctIndex": 1, "subject": "Parasitology", "explanation": "Hookworm infestation is called ancylostomiasis."},
    {"id": 6, "question": "Active management of third stage of labour is", "options": ["Uterine massage, CCT and oxytocin", "CCT, massage, oxytocin", "CCT, oxytocin and massage", "Oxytocin, CCT and uterine massage"], "correctIndex": 3, "subject": "Midwifery", "explanation": "Active management includes oxytocin, controlled cord traction (CCT), and uterine massage."},
    {"id": 7, "question": "The commonest site of hydatid cyst is", "options": ["Brain", "Lungs", "Spleen", "Liver"], "correctIndex": 3, "subject": "Pathology", "explanation": "Liver is the most common site for hydatid cyst."},
    {"id": 8, "question": "To be able to estimate and predict the future outcome is called", "options": ["Forecasting", "Programming", "Budgeting", "Scheduling"], "correctIndex": 0, "subject": "Nursing Management", "explanation": "Forecasting is estimating and predicting future outcomes."},
    {"id": 9, "question": "Which of the following is not an acute respiratory infection", "options": ["Sore throat", "Bronchial asthma", "Common cold", "Pneumonia"], "correctIndex": 1, "subject": "Respiratory", "explanation": "Bronchial asthma is a chronic condition, not an acute respiratory infection."},
    {"id": 10, "question": "Jeevan jal contains", "options": ["NaCl, NaHCO3, KCl and glucose", "NaCl, KHCO3, KCl, Glucose", "NaCl, NaHCO3, CaCl2, Glucose", "NaCl, KCl, lactate, glucose"], "correctIndex": 0, "subject": "Pharmacology", "explanation": "Jeevan jal contains sodium chloride, sodium bicarbonate, potassium chloride and glucose."},
    {"id": 11, "question": "The life span of the Erythrocytes in the Circulation is", "options": ["120 Days", "100 Days", "90 days", "80 days"], "correctIndex": 0, "subject": "Physiology", "explanation": "Erythrocytes circulate for about 120 days."},
    {"id": 12, "question": "The pulmonary artery carries", "options": ["Oxygenated blood", "Deoxygenated blood", "Calcium", "Protein"], "correctIndex": 1, "subject": "Anatomy", "explanation": "Pulmonary artery carries deoxygenated blood from heart to lungs."},
    {"id": 13, "question": "These are female gonads and they lie in a shallow fossa on the lateral walls of the pelvis", "options": ["Fallopian tubes", "Ovaries", "Uterus", "Ligaments"], "correctIndex": 1, "subject": "Anatomy", "explanation": "Ovaries are the female gonads located in the pelvic cavity."},
    {"id": 14, "question": "A structured plan which provides clear picture about the problem, reason, objectives, and action for nurses to render nursing care is", "options": ["Lesson plan", "Nursing care plan", "Treatment plan", "Admission plan"], "correctIndex": 1, "subject": "Nursing Process", "explanation": "Nursing care plan outlines problems, objectives and nursing actions."},
    {"id": 15, "question": "It is the palpable bounding of blood flow noted at various points on the body", "options": ["Temperature", "Pulse", "Heart rate", "Blood pressure"], "correctIndex": 1, "subject": "Vital Signs", "explanation": "Pulse is the palpable bounding of blood flow in arteries."},
    {"id": 16, "question": "Patient is often kept in side lying position post operation to", "options": ["Clear airway", "Clear Circulation", "Prevent from vomiting", "Electrolyte balancing"], "correctIndex": 2, "subject": "Surgical Nursing", "explanation": "Side-lying position helps prevent aspiration from vomiting post-surgery."},
    {"id": 17, "question": "An infection and inflammation of the lungs with consolidation and exudation is", "options": ["Pulmonary tuberculosis", "Pleurisy", "Pneumonia", "Bronchitis"], "correctIndex": 2, "subject": "Respiratory", "explanation": "Pneumonia involves lung inflammation with consolidation and exudation."},
    {"id": 18, "question": "Associated with rapidly progression of infection has high fever, dyspnea rapid pulse heart murmur is", "options": ["Myocarditis", "Bronchitis", "Acute infective endocarditis", "Cardiac failure"], "correctIndex": 2, "subject": "Cardiology", "explanation": "Acute infective endocarditis presents with fever, dyspnea and heart murmur."},
    {"id": 19, "question": "In a discussion, 4-8 persons who are qualified to talk about sit and discuss a given probable is", "options": ["Panel discussion", "Workshop", "Group Discussion", "Symposium"], "correctIndex": 0, "subject": "Nursing Education", "explanation": "Panel discussion involves 4-8 qualified persons discussing a topic."},
    {"id": 20, "question": "It is unpleasant experience of life, causes may be internal, person may experience changing environment, job, loss of family members etc.", "options": ["Stress", "Psychosis", "Anxiety", "Depression"], "correctIndex": 0, "subject": "Mental Health", "explanation": "Stress is an unpleasant experience caused by various life changes."},
    {"id": 21, "question": "The uterus is about between halfway between the symphysis pubis and umbilicus at", "options": ["12 weeks", "22 Weeks", "16 Weeks", "20 weeks"], "correctIndex": 2, "subject": "Obstetrics", "explanation": "At 16 weeks, uterus is midway between symphysis pubis and umbilicus."},
    {"id": 22, "question": "Contraction increase to more than 40 seconds and fetal descends begin in", "options": ["4th stage of labour", "2nd stage of labour", "3rd stage of labour", "1st stage of labour"], "correctIndex": 3, "subject": "Obstetrics", "explanation": "In first stage of labour, contractions exceed 40 seconds and fetus descends."},
    {"id": 23, "question": "The uterus may be at the level of the umbilicus or slightly above the umbilicus in", "options": ["6 days of postpartum", "6 weeks of postpartum", "24 hours after birth", "Immediate after birth"], "correctIndex": 2, "subject": "Postpartum", "explanation": "Uterus is at umbilicus level 24 hours after birth."},
    {"id": 24, "question": "A child who has committed an offence (disobedient, behaviour problem, and indulge antisocial practices) can be seen in", "options": ["Juvenile delinquency", "Psychosis", "Depression", "Drug addiction"], "correctIndex": 0, "subject": "Mental Health", "explanation": "Juvenile delinquency refers to antisocial behavior in children."},
    {"id": 25, "question": "The person lives in dream world of his own, this condition is...", "options": ["Neurosis", "Psychosis", "Depression", "Drug addiction"], "correctIndex": 1, "subject": "Mental Health", "explanation": "Psychosis involves loss of contact with reality and living in a dream world."},
    {"id": 26, "question": "A client is receiving anticoagulant the nursing care should include the observation for", "options": ["Nausea", "Epistaxis", "Headache", "Chest pain and vomiting"], "correctIndex": 1, "subject": "Pharmacology", "explanation": "Epistaxis (nosebleed) is a sign of anticoagulant overdose."},
    {"id": 27, "question": "A client is receiving anticoagulant the nursing care should include the observation for", "options": ["Nausea", "Ecchymosis and petechiae", "Painful menstruation and backache", "Early osteoporosis"], "correctIndex": 1, "subject": "Pharmacology", "explanation": "Ecchymosis and petechiae indicate bleeding due to anticoagulants."},
    {"id": 28, "question": "Antibodies are produced by", "options": ["Eosinophils", "Plasma cells", "Erythrocytes", "Lymphocytes"], "correctIndex": 1, "subject": "Immunology", "explanation": "Plasma cells (differentiated B cells) produce antibodies."},
    {"id": 29, "question": "Endometriosis is characterized by", "options": ["Amenorrhea", "Ecchymosis and petechiae", "Painful menstruation and backache", "Early osteoporosis"], "correctIndex": 2, "subject": "Gynecology", "explanation": "Endometriosis causes painful menstruation (dysmenorrhea) and backache."},
    {"id": 30, "question": "The clients with hepatitis are instructed never to", "options": ["Drink unboiled water", "Donate blood", "Smoke", "Take fatty blood"], "correctIndex": 1, "subject": "Communicable Diseases", "explanation": "Hepatitis patients should never donate blood to prevent transmission."},
    {"id": 31, "question": "Sharp instruments are sterilized under", "options": ["Dry heat", "Boiling", "Fumigation", "Radiation"], "correctIndex": 0, "subject": "Nursing Procedures", "explanation": "Sharp instruments are sterilized using dry heat to prevent damage."},
    {"id": 32, "question": "Most spontaneous abortion are mainly caused by", "options": ["Embryonic defect", "Congenital defect", "Psychological trauma", "Physical trauma"], "correctIndex": 0, "subject": "Obstetrics", "explanation": "Most spontaneous abortions are caused by embryonic chromosomal defects."},
    {"id": 33, "question": "In fetal blood vessels the oxygen content is high in the", "options": ["Ductus arteriosus", "Pulmonary artery", "Ductus venosus", "Umbilical artery"], "correctIndex": 2, "subject": "Embryology", "explanation": "Ductus venosus carries oxygenated blood from umbilical vein to inferior vena cava."},
    {"id": 34, "question": "Effective communication with client means", "options": ["Clearly writing", "Smoothly talking with the client", "Listening quietly", "Patient feedback of your question"], "correctIndex": 3, "subject": "Communication", "explanation": "Effective communication involves getting patient feedback."},
    {"id": 35, "question": "The first steps of counseling is", "options": ["Finding the situation", "Discuss about alternatives", "Sharing of necessary knowledge", "Building a good relationship and trust"], "correctIndex": 3, "subject": "Counseling", "explanation": "First step of counseling is building rapport and trust."},
    {"id": 36, "question": "Which of the following in Nepalese context is a cold food?", "options": ["Green leafy vegetables", "Beans", "Pulses", "Turmeric"], "correctIndex": 0, "subject": "Nutrition", "explanation": "Green leafy vegetables are considered cold foods in Nepalese context."},
    {"id": 37, "question": "Deficiency of calcium in older adults causes", "options": ["Night blindness", "Gingivitis", "Stomatitis", "Osteoporosis"], "correctIndex": 3, "subject": "Nutrition", "explanation": "Calcium deficiency leads to osteoporosis in older adults."},
    {"id": 38, "question": "Occurrence of lice is greater in", "options": ["Older people", "Children", "Mainly women", "Adolescents"], "correctIndex": 1, "subject": "Community Health", "explanation": "Lice infestation is more common in children."},
    {"id": 39, "question": "Prior to the pelvic examination the client should be encouraged to", "options": ["Take a soap water enema", "Have the vulva and perineum", "Clean the Vulva", "Empty the bladder"], "correctIndex": 3, "subject": "Gynecology", "explanation": "Patient should empty bladder before pelvic examination."},
    {"id": 40, "question": "Epidemiological triad is", "options": ["Agent host and environment", "Vector host and environment", "Environment and vector", "Agent"], "correctIndex": 0, "subject": "Epidemiology", "explanation": "Epidemiological triad consists of agent, host, and environment."},
    {"id": 41, "question": "Tranquilizers are substances mainly used for the treatment of", "options": ["Cancer", "Mental illness", "Physical disorder", "During wound illness"], "correctIndex": 1, "subject": "Pharmacology", "explanation": "Tranquilizers are used to treat mental illness and anxiety."},
    {"id": 42, "question": "Aspirin is the name of organic compound", "options": ["Hydroxyl benzoic acid", "Phenylsalicylate", "Acetyl salicylic acid", "Ethyl salicylate"], "correctIndex": 2, "subject": "Pharmacology", "explanation": "Aspirin is acetylsalicylic acid."},
    {"id": 43, "question": "Excessive vomiting during pregnancy is called", "options": ["Morning sickness", "Nephrotic syndrome", "Hyperemesis gravidarum", "Ectopic pregnancy"], "correctIndex": 2, "subject": "Obstetrics", "explanation": "Hyperemesis gravidarum is severe vomiting during pregnancy."},
    {"id": 44, "question": "Denominator in perinatal mortality is", "options": ["Still birth", "Live Birth", "All births", "All of the above"], "correctIndex": 2, "subject": "Epidemiology", "explanation": "Perinatal mortality denominator includes all births (still + live)."},
    {"id": 45, "question": "A Client has a temperature of 99.8 degree F. This temperature can be converted to", "options": ["36.5 C", "37 C", "37.7 C", "38.2 C"], "correctIndex": 2, "subject": "Vital Signs", "explanation": "99.8 F = (99.8-32)*5/9 = 37.7 C."},
    {"id": 46, "question": "The major route of transmission of hepatitis A is", "options": ["Perinatal transmission", "Sexual transmission", "Fecal-oral transmission", "Parenteral transmission"], "correctIndex": 2, "subject": "Communicable Diseases", "explanation": "Hepatitis A is transmitted through fecal-oral route."},
    {"id": 47, "question": "Road to health indicates that a child is", "options": ["Mentally healthy", "Completed the immunization", "Growing normally", "Free from Communicable disease"], "correctIndex": 2, "subject": "Pediatrics", "explanation": "Road to Health card indicates normal growth of a child."},
    {"id": 48, "question": "Coffee and tea contains caffeine so they are", "options": ["Sedatives", "Hypnotics", "Stimulant", "Depression"], "correctIndex": 2, "subject": "Pharmacology", "explanation": "Caffeine is a central nervous system stimulant."},
    {"id": 49, "question": "Sand flies transmitted the disease", "options": ["Typhoid", "Kala-azar", "Typhus fever", "Cholera"], "correctIndex": 1, "subject": "Communicable Diseases", "explanation": "Sand flies transmit kala-azar (visceral leishmaniasis)."},
    {"id": 50, "question": "Protein requirement is highest for", "options": ["Menstruating women", "Sick person", "Pregnant women", "Lactating women"], "correctIndex": 3, "subject": "Nutrition", "explanation": "Lactating women have the highest protein requirement."},
]

write_json("data/en/it/set4.json", IT_SET1)
write_json("data/ne/it/set4.json", IT_SET1)
write_json("data/en/it/set5.json", IT_SET2)
write_json("data/ne/it/set5.json", IT_SET2)
print("Wrote IT set4 and set5 (100 real questions from nepallaxman.com.np + sumitsahani.com.np)")

write_json("data/en/nursing/set4.json", NURSING_SET1)
write_json("data/ne/nursing/set4.json", NURSING_SET1)
write_json("data/en/nursing/set5.json", NURSING_SET2)
write_json("data/ne/nursing/set5.json", NURSING_SET2)
print("Wrote Nursing set4 and set5 (100 real questions from gyanmark.com)")

# =====================================================================
# Update tests.json for IT and Nursing to unlock set4 and set5
# =====================================================================

for lang in ['en', 'ne']:
    # Update IT tests.json
    it_tests_path = f"data/{lang}/it/tests.json"
    with open(it_tests_path, 'r', encoding='utf-8') as f:
        it_tests = json.load(f)
    
    for test in it_tests:
        set_num = int(test['id'].replace('set', ''))
        if set_num <= 2:
            test['locked'] = False
        elif set_num in [3, 4, 5]:
            test['locked'] = False
        else:
            test['locked'] = True
    
    with open(it_tests_path, 'w', encoding='utf-8') as f:
        json.dump(it_tests, f, ensure_ascii=False, indent=4)
    
    # Update Nursing tests.json
    nursing_tests_path = f"data/{lang}/nursing/tests.json"
    with open(nursing_tests_path, 'r', encoding='utf-8') as f:
        nursing_tests = json.load(f)
    
    for test in nursing_tests:
        set_num = int(test['id'].replace('set', ''))
        if set_num <= 2:
            test['locked'] = False
        elif set_num in [3, 4, 5]:
            test['locked'] = False
        else:
            test['locked'] = True
    
    with open(nursing_tests_path, 'w', encoding='utf-8') as f:
        json.dump(nursing_tests, f, ensure_ascii=False, indent=4)

print("Updated tests.json for IT and Nursing")
print("Done! Real portal questions have been integrated.")
